services:
  builderai-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - builderai-dev-network

networks:
  builderai-dev-network:
    driver: bridge
