version: '3.8'

services:
  # Main Application
  builderai-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Database Configuration
      - DATABASE_URL=postgresql://builderai:builderai123@postgres:5432/builderai_dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=builderai_dev
      - DB_USER=builderai
      - DB_PASSWORD=builderai123
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # MinIO S3 Configuration
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin123
      - S3_BUCKET_NAME=builderai-files
      - S3_REGION=us-east-1
      - S3_FORCE_PATH_STYLE=true
      - S3_USE_SSL=false
      # JWT Configuration
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
      - JWT_REFRESH_SECRET=dev-refresh-secret-key-change-in-production
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      # File Upload Configuration
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=pdf,doc,docx,txt,md,json,csv,xlsx
      - UPLOAD_PATH=/uploads
      # Development Configuration
      - LOG_LEVEL=debug
      - ENABLE_SWAGGER=true
      - CORS_ORIGIN=http://localhost:8080
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - builderai-dev-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=builderai_dev
      - POSTGRES_USER=builderai
      - POSTGRES_PASSWORD=builderai123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - builderai-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - builderai-dev-network

  # MinIO S3-Compatible Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - builderai-dev-network

  # MinIO Client (for bucket initialization)
  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - ./scripts/init-minio.sh:/init-minio.sh
    command: sh /init-minio.sh
    networks:
      - builderai-dev-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  builderai-dev-network:
    driver: bridge
